 name: CI
 on: [push]
 jobs:
   build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v1
       - name: Use Node.js 8.x 
         uses: actions/setup-node@v1
         with:
           registry-url: https://npm.pkg.github.com/
           node-version: 8.x
           scope: '@dalenguyen'
       - name: npm install, build, and test
         run: |
           npm install
           npm run build --if-present
           npm test   
       - name: build docker images
         uses: dakario/docker-build-push-action@master
         with:
          name: modoulobolysow/test-demo-meetup
          username: ${{ secrets.docker_login}}
          password: ${{ secrets.docker_password}}
